### PR TITLE
MRG: refactor sketching utilities

### PR DESCRIPTION
**Pull request by bluegenes**
- refactor for reusability: move all generalized sketch building utils --> `utils/buildutils.rs`
- do minor refactoring to use `sourmash::encodings::HashFunctions` for `moltype`, created `Abund` enum.
- requires https://github.com/sourmash-bio/sourmash/pull/3344 to use `Hash` for `sourmash::encodings::HashFunctions`

Related:
- https://github.com/sourmash-bio/sourmash_plugin_directsketch/issues/113

### CODE REVIEW

**Comment by bluegenes** [comment]
@ctb ready for review. No big changes, mostly just moved existing implementations.

**Review by ctb — APPROVED** [review]

**Comment by ctb** [comment]
Not sure how to sequence this with https://github.com/sourmash-bio/sourmash/pull/3344#pullrequestreview-2353095945, but I think the simplest might be to target `latest` on sourmash and then before a release of directsketch will cut a new release of sourmash. Seem ok?

Alternatively, can just let it hang for a bit until we release new version of sourmash.

**Comment by bluegenes** [comment]
I'm going to target `latest` and drop it in `main` for now so I can put up other PRs off of it. I'm not in a hurry for release - no functionality changes here (or currently planned). But I'll make a draft PR to update to the next sourmash core release.

**Comment by ctb** [comment]
> I'm going to target `latest` and drop it in `main` for now so I can put up other PRs off of it. I'm not in a hurry for release - no functionality changes here (or currently planned). But I'll make a draft PR to update to the next sourmash core release.

sounds good! we'll be in more of a hurry for a sourmash release over in branchwater once I get the `MultiCollection` PR figured out ;)

**Pull request merged**
